
#!/bin/bash
#Created by : ravinayag@gmail.com | Ravi Vasagam


clear  #Need to remove on final stage
trap 'echo got SIGINT' SIGINT #### Control C
trap ' '2 20
trap "" TSTP
export IGNOREEOF=20   # Contrl+D
set -o ignoreeof
source .env
source .c.env

echo  -e $LBCOLOR"This is my personal project and created for the Hyperledger platforms.
Please do complete the prerequisites to perform Hyperledger samples generated by this Starter Kit tool.

You Should have Linux Ubuntu system - version 16 ~ 20 to install the prereq's script.
You can contact me anytime or create a issue at 17114156-080@uog.edu.pk"$NONE

echo
echo -e $GRCOLOR " .."$NONE
echo
echo  -e $LBCOLOR"."$NONE
source $HL_CFG_PATH/hlstartup/00_StartCustomHL.sh
source $HL_CFG_PATH/hlstartup/01_networkinfo.sh

## Custominzing the Configurations
checkenv

## Selecing the Blockchain Network
selBCNet


customDom
echo  -e $BCOLOR"##################################################################"$NONE && echo ""
customOrg
echo  -e $BCOLOR"##################################################################"$NONE && echo ""
customPeer
echo  -e $BCOLOR"##################################################################"$NONE && echo ""
customOrder
echo  -e $BCOLOR"##################################################################"$NONE && echo ""
customCA
echo  -e $BCOLOR"##################################################################"$NONE && echo ""
customChannel


## Syschannel variable Setting
setsyschl


## Checking the 3rd Organisation , Orderers and generate the custom files.
checkORG3

## Updating the Custom Values
SEDing
#SEDingfiles2

## Adding the Org's and updating the Values
addorgsed


## Cleaning the previous dir's and  Copying the container Script 
## As per Version Requirements
rmovecrypto
ScriptVerCopy

## Custom Select for Consensus/ Orderer Type  and Updating the values to dockercompose files.
#source $HL_CFG_PATH/hlstartup/01_networkinfo.sh
selconsensus
SEDordraft
## Updating the Confgitx Versions and generate Artifacts.
createChannelArtifacts

## Updating the Private keys to CA config file.s
replKeys

## Custom to Select Docker Containers SOLO/SWARM/K8s
#source $HL_CFG_PATH/hlstartup/01_networkinfo.sh
selvirtcontainer

## Custom Option to select Sample Chaincodes.
source .env
source $HL_CFG_PATH/hlstartup/04_Fabsamplecc.sh
#selccode
#source $HL_CFG_PATH/hlstartup/01_networkinfo.sh
AskconfEmail
## Ask for Explorer Start
exit 123
exit 1